baseURL = "https://www.studioneon.nl/"
languageCode = "en-us"
title = "Studio Neon"
theme = "neon"
[markup.goldmark.renderer]
   unsafe = true

[taxonomies]
   tag = "tags"
   category = "categories"
[outputs]
  home = ["HTML", "RSS", "JSON"]