[build]
command = "pm run tinacms build && hugo"
publish = "public"

HUGO_VERSION = "0.110.0"

[context.production.environment]
HUGO_VERSION = "0.110.0"

[context.deploy-preview]
command = "npm run build:preview"
