---
label: 'Meta '
hide_body: false
is_partial: true
display_field: meta_title
fields:
- type: text
  name: meta_title
  label: Meta title
- type: textarea
  name: meta_description
  label: Meta Description
